### ISSUE TITLE
Images REST API and Swagger

### ISSUE THREAD

**Issue by VerticalHeretic** [VerticalHeretic/APiP-Project#5]
## DOD (Definition of Done)
- [x] Image upload endpoint
- [x] Image getting endpoint
- [x] Image processing status endpoint
- [x] Swagger for the endpoints as form of documentation

**Comment by VerticalHeretic** [comment]
https://www.youtube.com/watch?v=FZbYXey6dJw&t=393s

**Comment by LSWarss** [comment]
@psztefko postman collection link: https://app.getpostman.com/join-team?invite_code=86bcc37037381ffecd21d9686b687595&target_code=149df72e66d263261a08fda57167659b
